CREATE DATABASE DuAn1
go
USE DuAn1
go

-- NhanVien
CREATE TABLE NhanVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
HoTen NVARCHAR(100) DEFAULT NULL,
GioiTinh BIT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
SDT VARCHAR(10) NOT NULL,
Email VARCHAR(100) NOT NULL,
TrangThai INT DEFAULT 0,
ChucVu INT NOT NULL,
MatKhau varchar(50) not null,
CreatedDate DATE,
LastModifiedDate DATE
)


GO
-- KhachHang
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
HoTen NVARCHAR(100),
Sdt VARCHAR(10) DEFAULT NULL,
Email VARCHAR(100) DEFAULT NULL UNIQUE,
DiaChi NVARCHAR(100) DEFAULT NULL,
CapBac INT DEFAULT NULL,
CreatedDate DATE,
LastModifiedDate DATE
)

GO
--HoaDon
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
Ma VARCHAR(100) UNIQUE,
NgayTao DATE DEFAULT NULL,
TienKhachTra MONEY NULL,
TienThua MONEY NULL,
TienCK MONEY NULL,
TongTien MONEY NULL,
HinhThuc INT NULL,
TinhTrang INT DEFAULT 0,
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- SanPham
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
TrangThai int,
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- CPU
CREATE TABLE CPU(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- Ram
CREATE TABLE Ram(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- CardMH
CREATE TABLE CardMH(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- OCung
CREATE TABLE OCung(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- Hang
CREATE TABLE Hang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten NVARCHAR(100),
CreatedDate DATE,
LastModifiedDate DATE
)
GO

-- ChiTietSP
CREATE TABLE ChiTietSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaCTSP VARCHAR(100) UNIQUE,
IdSanPham UNIQUEIDENTIFIER,
IdCPU UNIQUEIDENTIFIER,
IdHang UNIQUEIDENTIFIER,
IdRam UNIQUEIDENTIFIER,
IdCardMH UNIQUEIDENTIFIER,
IdOCung UNIQUEIDENTIFIER,
Gia MONEY DEFAULT 0,
Serial VARCHAR(12) UNIQUE NULL,
TinhTrang INT,
CreatedDate DATE,
LastModifiedDate DATE
)

GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
TenSP nvarchar(50),
DonGia DECIMAL(20,0) DEFAULT 0,
TrangThai INT NULL,
CreatedDate DATE,
LastModifiedDate DATE
)

-- SerialDaBan
CREATE TABLE SerialDaBan(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHDCT UNIQUEIDENTIFIER,
Ma VARCHAR(100) UNIQUE,
CreatedDate DATE,
LastModifiedDate DATE
)

-- KhuyenMai
CREATE TABLE KhuyenMai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) NULL,
LoaiKhuyenMai INT NULL,
GiaTriKM MONEY NULL,
NgayBatDau DATE NULL,
NgayKetThuc DATE NULL,
TrangThai INT NULL,
CreatedDate DATE,
LastModifiedDate DATE
)


--SanPhamKhuyenMai
CREATE TABLE SanPhamKhuyenMai(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdChiTietSanPham UNIQUEIDENTIFIER,
IdKhuyenMai UNIQUEIDENTIFIER,
CreatedDate DATE,
LastModifiedDate DATE
)

-- HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)--đ

-- HoaDon - NhanVien
ALTER TABLE HoaDon ADD FOREIGN KEY (IdNV) REFERENCES NhanVien(Id) --đ

--HoaDonChiTiet - HoaDon
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY (IdHoaDon) REFERENCES HoaDon(Id) --đ

--HoaDonChiTiet - ChiTietSanPham
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY (IdChiTietSP) REFERENCES ChiTietSP(Id) --đ

-- ChiTietSP - SanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSanPham) REFERENCES SanPham(Id) --đ
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdCPU) REFERENCES CPU(Id) --đ
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdRam) REFERENCES Ram(Id) --đ
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdCardMH) REFERENCES CardMH(Id) --đ
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdOCung) REFERENCES OCung(Id) --đ
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdHang) REFERENCES Hang(Id) --đ

--SanPhamKhuyenMai -- ChiTietSP
ALTER TABLE SanPhamKhuyenMai ADD FOREIGN KEY (IdChiTietSanPham) REFERENCES ChiTietSP(Id)

--SanPhamKhuyenMai -- KhuyenMai
ALTER TABLE SanPhamKhuyenMai ADD FOREIGN KEY (IdKhuyenMai) REFERENCES KhuyenMai(Id)

ALTER TABLE SerialDaBan ADD FOREIGN KEY (IdHDCT) REFERENCES HoaDonChiTiet(Id)